### ISSUE TITLE
Player Connection Create Error

### ISSUE THREAD

**Issue by ishh-xd** [parasop/poru#100]
# Error

- Player create connection shows this error (image).

# To Reproduce

(I'm unsure but this error happens randomly)
- Add a random song then add random player filters, then after few time of track end. Disconnect the player. The player join function shows this error.
- This doesn't work everytime but in most cases like after 5-6 times of randomly playing songs and doing this, shows this error.

# Error Image

![Image](https://github.com/parasop/poru/assets/88816438/899e5b26-147f-4379-94d5-7fe1d92701df)

**Comment by ishh-xd** [comment]
## And yes, I've added the node's name. So that's not an issue.

**Comment by ishh-xd** [comment]
This error also occurs when player.destroy() is ran. Then try to create connection.

**Comment by bitwise74** [comment]
are you sure this isn't related to lavalink itself?

**Comment by ishh-xd** [comment]
No it wasn't related to lavalink. 
(It was happening due to addition of    Voice Region  in player connection.) I removed it and now it's fixed.

**Comment by ishh-xd** [comment]
Fixed: It was happening due to addition of Voice Region in player connection.
