### ISSUE TITLE
Issue Autoplay

### ISSUE THREAD

**Issue by OxydeDev1789** [parasop/poru#109]
Hello I tried the Autoplay() function this last one skips the music by putting a music found by the module but the problem when the music ends it does not try to find another music but it has stopped playing why not put it in the Loop function

**Comment by Joniii11** [comment]
You need to trigger it by yourself. Just add a event listener to trackEndEvent and check if there are no tracks in queue if so trigger autoplay

**Comment by parasop** [comment]
solved
