### ISSUE TITLE
Need information

### ISSUE THREAD

**Issue by pasindu20** [parasop/poru#22]
1. Is this package support sharding ?
2. Is this package better then shoukaku  ?
3. Is this package easy to use ?
4. what the benefits of using this package ? 
5. Is this package like erela.js ?
6. Is this package has player.set feature like (settings temp data `player.set("track", player.queue.current)` if i do `player.get("track")` this will give the info i saved ?
7.  Is this package use high ram usage or not ?

 I'm in kind a hurry so can you give the information fast as possible
 (my bot is currently using erela.js so its getting tons of ram usage)

**Comment by parasop** [comment]
1. Ofc this works fine with any sharding client 
2. If you are comparing features than poru is better
3. Yes this package make your code easy to use and understand 
4. Everything is inbuilt and works good with large bots
5. No this isn't erela
6. Yes you can do it player.track = player.currentTrack

=> we have inbuilt support for spotify,apple music and deezer that no one can provide you

**Comment by pasindu20** [comment]
> 1. Ofc this works fine with any sharding client
> 2. If you are comparing features than poru is better
> 3. Yes this package make your code easy to use and understand
> 4. Everything is inbuilt and works good with large bots
> 5. No this isn't erela
> 6. Yes you can do it player.track = player.currentTrack
> 
> => we have inbuilt support for spotify,apple music and deezer that no one can provide you

update the msg on 6. i mean it can save data on cache ?

**Comment by parasop** [comment]
yes you can set data on cache easily 
For example 

player.name = "test";
player.track = { "test: "test"}
player.data = ["0" "1","2"]

**Comment by parasop** [comment]
you can access it via player.data

**Comment by parasop** [comment]
player.data[0]
it will be name

**Comment by pasindu20** [comment]
> player.data[0] it will be name
 compare to other lavalink packages is this use lot of ram
 if i set more data on cache system it use more ram ?

**Comment by parasop** [comment]
> > player.data[0] it will be name
> 
> compare to other lavalink packages is this use lot of ram if i set more data on cache system it use more ram ? if this package use any big bots so i can check it

player data doesn't take a lot of memory

**Comment by pasindu20** [comment]
> if you disable your discord.js cache than you 70 to 80% ram will save

is there any guide  for disable the djs cache ?

**Comment by parasop** [comment]
![Screenshot_20220720-131228_Discord](https://user-images.githubusercontent.com/63485824/182447629-53714439-89ec-4473-98fb-b645e8ca2234.jpg)
You can add this In your client options

**Comment by pasindu20** [comment]
Thank you i hope this package fix my memory issue

**Comment by pasindu20** [comment]
> ![Screenshot_20220720-131228_Discord](https://user-images.githubusercontent.com/63485824/182447629-53714439-89ec-4473-98fb-b645e8ca2234.jpg) You can add this In your client options

where do i get cachemanager option docs ?
