### ISSUE TITLE
Add more events

### ISSUE THREAD

**Issue by pasindu20** [parasop/poru#31]
Add more events to poru ex-
`playerCreate` =fire if player created
`playerDestory` = fire if player get destoryed (is require if user disconnect player from vc or command destory)
`playerMove` = fire if player moved (is require for if player moved set new voice channel) 
add this events soon as possible

**Comment by parasop** [comment]
playerMove works same as voiceStateUpdate

**Comment by pasindu20** [comment]
> playerMove works same as voiceStateUpdate

what about player create and playerDestroy
i really need this two

**Comment by pasindu20** [comment]
> > playerMove works same as voiceStateUpdate
> 
> what about player create and playerDestroy i really need this two

i start moving bot to this npm but i can't because there no player destroy event

**Comment by pasindu20** [comment]
can you add that events fast as possibe

**Comment by pasindu20** [comment]
> playerMove works same as voiceStateUpdate

mmm i don't get it , i currently using this npm that has no playermove event but it has this
```js
private onVoiceStateUpdate(oldState: any, newState: any): void {
    if (!this.kazagumo || oldState.id !== this.client.user.id) return;

    const newChannelId = newState.channelID || newState.channelId;
    const oldChannelId = oldState.channelID || oldState.channelId;
    const guildId = newState.guild.id;

    const player = this.kazagumo.players.get(guildId);
    if (!player) return;

    let state = 'UNKNOWN';
    if (!oldChannelId && newChannelId) state = 'JOINED';
    else if (oldChannelId && !newChannelId) state = 'LEFT';
    else if (oldChannelId && newChannelId && oldChannelId !== newChannelId) state = 'MOVED';

    if (state === 'UNKNOWN') return;

    this.kazagumo.emit(Events.PlayerMoved, player, state, { oldChannelId, newChannelId });
  }
  ```

**Comment by pasindu20** [comment]
> playerMove works same as voiceStateUpdate

example, also add playercreate and playerdestroy events soon as possible i really need them

**Comment by pasindu20** [comment]
> Add more events to poru ex- `playerCreate` =fire if player created `playerDestory` = fire if player get destoryed (is require if user disconnect player from vc or command destory) `playerMove` = fire if player moved (is require for if player moved set new voice channel) add this events soon as possible

i can't recode the bot this events are **necessary**

**Comment by pasindu20** [comment]
can you add plaermove even't like erela.js

**Comment by parasop** [comment]
new update will come in this week I will try to add this

**Comment by pasindu20** [comment]
> new update will come in this week I will try to add this

also don't add create connection options to shard id (on sharded bot it hard to calculate it not message.guild.shardId i mean save data and calliing it and join channel like 24/7 system)

**Comment by pasindu20** [comment]
> new update will come in this week I will try to add this

what the date of new update coming up

**Comment by pasindu20** [comment]
I need those 3 events fast as possible im kind in a hurry like i need to recode bot fast as possible
currently i can't switch because of there no playerDestory, playerMove, playerCreate added

**Comment by parasop** [comment]
> I need those 3 events fast as possible im kind in a hurry like i need to recode bot fast as possible currently i can't switch because of there no playerDestory, playerMove, playerCreate added

what things you do inside this event contact me on discord

**Comment by parasop** [comment]
Now you can use
playerCreate 
playerDestroy 
Events
