### ISSUE TITLE
Change this on new update

### ISSUE THREAD

**Issue by pasindu20** [parasop/poru#32]
currently loop method has integer right so it hard to understand so i suggest

disableloop = `loop: 'none'`
trackloop = `loop: 'track'`
queueloop `loop: 'queue'`
change integer and add it string option

**Comment by parasop** [comment]
0 = none
1 = track 
2 = queue 

isn't hard to understand
Also integer take less ram compare to string

**Comment by pasindu20** [comment]
Ok
