### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by pasindu20** [parasop/poru#33]
1. how do i enable/disable autoresume on this package?
2. how do i optimize memory on this like if player start it slowly getting more and more ram so any way to stop that?

**Comment by parasop** [comment]
you can add auto resume by adding it in poru option 

you can look at here
https://poru.parasdocs.tech

**Comment by parasop** [comment]
player doesn't take more ram until you add more tracks into queue

**Comment by pasindu20** [comment]
> player doesn't take more ram until you add more tracks into queue

Is there any way to limit it

**Comment by pasindu20** [comment]
How much ram take 50 tracks

**Comment by parasop** [comment]
100 to 200 byte per element of array

**Comment by pasindu20** [comment]
> 100 to 200 byte per element of array

how many tracks it fit on single array

**Comment by parasop** [comment]
> > 100 to 200 byte per element of array
> 
> how many tracks it fit on single array

You can add 2 carore+ elements in array
