### ISSUE TITLE
Add this on new update

### ISSUE THREAD

**Issue by pasindu20** [parasop/poru#34]
Add skip track method ex. `player.skip()`
*why is this package missing so many things*

**Comment by pasindu20** [comment]
> Add skip track method ex. `player.skip()` _why is this package missing so many things_

like on erela 
 player.skip() = skip to queue next songs
 player.stop() = stop the current playing track and clear the queue
 player.destory() = disconnect the player from vc
 
 so i suggest make skip() and stop() like erela

**Comment by parasop** [comment]
> > Add skip track method ex. `player.skip()` _why is this package missing so many things_
> 
> like on erela player.skip() = skip to queue next songs player.stop() = stop the current playing track and clear the queue player.destory() = disconnect the player from vc
> 
> so i suggest make skip() and stop() like erela

you should not compare any packages all packages have their own functions we can't make same name

**Comment by pasindu20** [comment]
Hmm
