### ISSUE TITLE
Expose player volume property

### ISSUE THREAD

**Issue by iniznet** [parasop/poru#36]
[The player volume](https://github.com/parasop/poru/blob/9a62cfd7e30829e792833449532160bca1d8cef6/src/Player.js#L39-L41) seems to be not exposed which results in getting  `Cannot read properties of undefined (reading 'volume')` error.
The docs wiki doesn't list the volume property either.

Let me know if you're also going to put it in the next update or if there's some mistake I do.

**Comment by iniznet** [comment]
My bad, seems it's a false positive after reviewing, there's some logic error within my code.

**Comment by parasop** [comment]
np next update will lauch
