### ISSUE TITLE
DefaultSearchPlatform

### ISSUE THREAD

**Issue by JamesBondee** [parasop/poru#45]
How to do  defaultplatform to search, everytime  it search ytsearch, im disabled youtube search in lavalink but im idk how to disable it bot side.

**Comment by parasop** [comment]
make defaultPlatform: "scsearch"

**Comment by parasop** [comment]
and when you search track use spotify or scsearch

**Comment by JamesBondee** [comment]
> make defaultPlatform: "scsearch"

Can y can write code example to do that please?

**Comment by JamesBondee** [comment]
Im maked Poru options defaultPlatform: "scsearch". But it searching yt and don't find any song because I disabled youtube search in lava link...

**Comment by JamesBondee** [comment]
Solved that, thanks.
