### ISSUE TITLE
resolve function bug

### ISSUE THREAD

**Issue by pasindu20** [parasop/poru#49]
if bot reslove track it not give right track it give random one not [0] track it search,
before 2-3 days it working fine now it got broke

**Comment by pasindu20** [comment]
i try this on other npm packages they are working fine.

**Comment by parasop** [comment]
what is your search platform?

**Comment by pasindu20** [comment]
on my custom bot i use ytsearch

**Comment by parasop** [comment]
poru doesn't touch any search result
It's comes from lavalink

**Comment by pasindu20** [comment]
but i haven't change or restart lavalink servers

**Comment by pasindu20** [comment]
or yt do some api changes ?

**Comment by pasindu20** [comment]
i search the song but it not playing what i provided it giving random song

**Comment by pasindu20** [comment]
its not lavalink issue i try 4 defferent lava server they all give same result but other npms are working

**Comment by pasindu20** [comment]
search is working fine but when i got to play track it not play [0] track it play random one

**Comment by pasindu20** [comment]
Im so sorry it was my mistake on my single mistake broke down all search result
