### ISSUE TITLE
Bug with poru

### ISSUE THREAD

**Issue by JamesBondee** [parasop/poru#53]
This bug already started for me a month ago.
I am experiencing an issue where music would just stop playing randomly. I get no errors or anything whenever this happens. Lavalink still sends events and still play's music according to the logs, though I think my bot just stops sending voice data to Discord...

**Comment by parasop** [comment]
> This bug already started for me a month ago. I am experiencing an issue where music would just stop playing randomly. I get no errors or anything whenever this happens. Lavalink still sends events and still play's music according to the logs, though I think my bot just stops sending voice data to Discord...

In which poru version?

you have to destroy player on queueEnd

**Comment by JamesBondee** [comment]
Im used poru v2 and v3 and all of that poru versions im get that bug.
Im have destroy player on queueEnd
