### ISSUE TITLE
Oceanic js Issue

### ISSUE THREAD

**Issue by BTX-ON-YT** [parasop/poru#60]
src/Poru.ts:195 needs to be changed to `if (guild) guild.shard.send(packet?.op, packet?.d);`

**Comment by BTX-ON-YT** [comment]
This still needs fixing paras implemented something but `sendWS` is not a function on the `shard` class

**Comment by BTX-ON-YT** [comment]
`guild.shard.sendWS` should be replaced with `guild.shard.send`

**Comment by parasop** [comment]
fixed
