### ISSUE TITLE
filters 

### ISSUE THREAD

**Issue by ukcai696969** [parasop/poru#69]
hello i’m having issues with the filters so i’m using lavalink v3.6.2 and the filters don’t work i’ll show you the lavalink error if you need it just disconnects from the lavalink server

**Comment by ukcai696969** [comment]
https://github.com/freyacodes/Lavalink/issues/855 there’s the lavalink issue i made

**Comment by UnschooledGamer** [comment]
I feel the problem is your code & some problem types of poru also

Can you show your code that you use for setting the filters?

**Comment by parasop** [comment]
> hello i’m having issues with the filters so i’m using lavalink v3.6.2 and the filters don’t work i’ll show you the lavalink error if you need it just disconnects from the lavalink server

can you show me where you using distortion filter

**Comment by ukcai696969** [comment]
its ok i deleted them
