### ISSUE TITLE
Receive user audio 

### ISSUE THREAD

**Issue by tony-ist** [parasop/poru#73]
Hi! Thanks for this library.

I develop a discord bot which needs to hear what people say to him and also plays music. I have recently switched from `ytdl-core-discord` to `Lavalink` and found your library. 

I had used `const connection = discordJsVoice.getVoiceConnection(guild.id)` to get discord.js connection and then `connection.receiver.subscribe` to get user audio stream before. Now I don't see any discord.js connection that I can get inside `poru`.

How can I listen to user speaking with `poru`?

**Comment by parasop** [comment]
You can send data to discord voice channels through poru lavalink doesn't provide functionality to listen other users audio
