### ISSUE TITLE
Missing types in TS declarations.

### ISSUE THREAD

**Issue by tobiO0310** [parasop/poru#80]
For example, the queue class extends Array, but it most likely would extend Array<Track>, since it's an array of tracks.
I am unsure if this was intentional, but if not, it would greatly assist me in using TypeScript.

The Poru class also seems to be missing a few types, such as the return type of the functions [`decodeTrack(s)`](https://github.com/parasop/poru/blob/v4/src/Poru.ts#L463), [`getLavalinkInfo`](https://github.com/parasop/poru/blob/v4/src/Poru.ts#L485), and [`getLavalinkStatus`](https://github.com/parasop/poru/blob/v4/src/Poru.ts#L494).

It's a really great package, but I'm having a bit of trouble with TypeScript regarding missing type declarations.

**Comment by parasop** [comment]
TypeScript issue will fix in next commit

**Comment by tobiO0310** [comment]
Thank you very much, have a lovely day!
