### ISSUE TITLE
Return Null

### ISSUE THREAD

**Issue by ErrorDoc404** [parasop/poru#88]
Response {
  tracks: undefined,
  loadType: undefined,
  playlistInfo: undefined
}

![image](https://github.com/parasop/poru/assets/35562217/1dca5f07-532c-4eb0-aba7-e45dbc9062de)

**Comment by ErrorDoc404** [comment]
![image](https://github.com/parasop/poru/assets/35562217/43b14ede-e286-49be-8e18-58dd831ae573)

**Comment by LucasB25** [comment]
console.log(resolve)

**Comment by batistace** [comment]
Did you switch from client.poru to client.manager??

**Comment by parasop** [comment]
mis match version of lavalink
